### ISSUE TITLE
export_alignment_myself.py

### ISSUE THREAD

**Issue by fanzhenxuan** [ZCWzy/preprocessForHugs#1]
您好，我再运行export_alignment_myself.py时出现了以下错误：
![Snipaste_2024-08-17_17-34-09](https://github.com/user-attachments/assets/f67f3f5d-342f-4e98-9a93-e14949f28b20)
似乎是因为pts_2d是不正确的，我打印了他的内容发现是一个数字，这是否有问题？他是否应该是一个包含两个值的数组？并发现它来自于
![Snipaste_2024-08-17_17-35-59](https://github.com/user-attachments/assets/755ab0b5-060b-46c1-a1eb-ec6085fb5c28)
代码中取值用的是picture['2d_joints'][0][0]，这是否有问题？
期待您的回复

**Comment by ZCWzy** [comment]
你好，感谢你用我的代码。picture['2d_joints']应该是类似
```
([111,111],
[222,222],
...
[333,333])
```
的二维数组，对于图片picture，picture[i]表示关节点 i 在图片上的坐标，具体的格式我记不清了。（你的这个输出数据数量级也不对，我怎么感觉好像还是4D-human的归一化坐标）
您的输入数据中，某张图片是否包含多个人物？
如果picture2d始终不对，可以参考[4d-human](https://github.com/shubham-goel/4D-Humans/issues/55#issuecomment-1773383934)，手动修改4d-human/demo.py的内容，使得输出结果正常（建议输出2d坐标点，用[drawpoint.py](https://github.com/ZCWzy/preprocessForHugs/blob/master/drawpoint.py)确认是否正确。这一步可以白嫖colab

**Comment by fanzhenxuan** [comment]
非常感谢您的回答，我了解到picture['2d_joints']来自于4D-humans/track.py所生成的pkl文件，并查看了PHALP中关于此pkl文件细节的描述，
![Snipaste_2024-08-18_13-22-14](https://github.com/user-attachments/assets/ef486f6b-1a6c-4249-8b47-60b601a43e79)
因此我生成的pkl文件应该是没有问题的，export_alignment_myself.py直接使用了该pkl文件，但您提到picture['2d_joints']的形式应该是二维数组，且我的数据数量级不正确，我是否缺少了从当前形式向二维数组进行转换的步骤？我是完全按照您的项目中run.sh进行执行的。
![Snipaste_2024-08-18_13-34-34](https://github.com/user-attachments/assets/a1f0ccb9-1e35-4a85-9292-58c0d101e8f7)
另外，我的图片中只有一个人物。我也尝试将目前的picture['2d_joints']按照两个一组生成矩阵，但这又会重新导致新的错误。
期待您的回复。

**Comment by ZCWzy** [comment]
> 非常感谢您的回答，我了解到picture['2d_joints']来自于4D-humans/track.py所生成的pkl文件，并查看了PHALP中关于此pkl文件细节的描述， ![Snipaste_2024-08-18_13-22-14](https://private-user-images.githubusercontent.com/128810235/358885929-ef486f6b-1a6c-4249-8b47-60b601a43e79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjE2MDgsIm5iZiI6MTcyMzk2MTMwOCwicGF0aCI6Ii8xMjg4MTAyMzUvMzU4ODg1OTI5LWVmNDg2ZjZiLTFhNmMtNDI0OS04YjQ3LTYwYjYwMWE0M2U3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNjA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjVhODk5MTY5Zjg1NTcxYmQwM2Q5M2U3Mzc4NTE4YzU1NDI1NWNjYmI1YzRiYzRkNWJlNjI5NWMzYjY4NzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E5zcz4-TUACwsXmKQq7TxTTtT4agY06x03NBBMwXnNI) 因此我生成的pkl文件应该是没有问题的，export_alignment_myself.py直接使用了该pkl文件，但您提到picture['2d_joints']的形式应该是二维数组，且我的数据数量级不正确，我是否缺少了从当前形式向二维数组进行转换的步骤？我是完全按照您的项目中run.sh进行执行的。 ![Snipaste_2024-08-18_13-34-34](https://private-user-images.githubusercontent.com/128810235/358886301-a1f0ccb9-1e35-4a85-9292-58c0d101e8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjE2MDgsIm5iZiI6MTcyMzk2MTMwOCwicGF0aCI6Ii8xMjg4MTAyMzUvMzU4ODg2MzAxLWExZjBjY2I5LTFlMzUtNGE4NS05MjkyLTU4YzBkMTAxZThmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNjA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2E5ODBlNDM2NzA4ZmE0N2IwYTUyZTI5ZjE2Y2I0M2IyM2NhNzNmMGJjY2U5NmE3NzIxOWFjMDRhNmYzZDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uSQOBV-q0vI7Y0reDmeJL0dVoBw8hPhBfHmcgb2drBc) 另外，我的图片中只有一个人物。我也尝试将目前的picture['2d_joints']按照两个一组生成矩阵，但这又会重新导致新的错误。 期待您的回复。


我看到你是
`cp ./outputs/results/demo_phalp.pkl 某某某/output/4d_humans/track_results.pkl`
你是直接用了来自于4D-humans/track.py生成的pkl吗，我在这个仓库里有个魔改的demo.py，用魔改的demo.py替换4d-human/demo.py，然后再执行python demo.py那一步（我在这个demo.py里写了一些数据转换的步骤，你有兴趣可以瞄一眼）

另外，附上我产生的run.sh
```
cd /root/4D-Humans
conda activate 4D-humans
python track.py video.source=/root/autodl-tmp/data/myself/output/4d_humans/phalp 
python demo.py --img_folder /root/autodl-tmp/data/myself/output/images     --out_folder ./demo_out --batch_size=48
cp ./outputs/results/track_result.pkl /root/autodl-tmp/data/myself/output/4d_humans/track_results.pkl
conda deactivate
```

（我去你也是autoDL）

**Comment by fanzhenxuan** [comment]
非常感谢您的回答，我更改后已经可以执行所有的数据处理流程，这是我得到的处理后的文件夹：
![Snipaste_2024-08-19_12-30-24](https://github.com/user-attachments/assets/cb64d28b-7fc9-4a03-83ea-68d767550140)
但与HUGS中的数据有一些差异：
![Snipaste_2024-08-19_12-35-17](https://github.com/user-attachments/assets/53debd93-e082-4656-b9ca-d433fd6bd043)
这是否是无关紧要的？
此外，我看到您已经可以使用HUG渲染自定义数据集，但HUGS中部分代码只针对于neuman数据集，如：
![Snipaste_2024-08-19_12-46-12](https://github.com/user-attachments/assets/6b50810c-c767-48f2-bfd9-17ddda57fe91)
![Snipaste_2024-08-19_12-46-26](https://github.com/user-attachments/assets/30651a97-517a-4bf6-9751-f57076759b90)
您能否告知您是如何对这些代码进行修改？并能否分享更多细节？
期待您的恢复。

**Comment by ZCWzy** [comment]
> 非常感谢您的回答，我更改后已经可以执行所有的数据处理流程，这是我得到的处理后的文件夹：这是否是无关紧要的？
此外，我看到您已经可以使用HUG渲染自定义数据集，但HUGS中部分代码只针对于neuman数据集，如：...您能否告知您是如何对这些代码进行修改？并能否分享更多细节？ 期待您的恢复。

@FFFFFzx 
关于
> 但与HUGS中的数据有一些差异...

我感觉是无关紧要的，我减少了neuman的一些流程，所以有几个文件夹并没有产生。（没有这几个文件夹也能运行hugs，但是对训练质量的影响我没有试过，如果你需要这几个文件夹，可以参考neuman的预处理，加上去即可。我去掉这几步的原因是那个单目深度估计很慢，而且没有这一步hugs也能运行）

关于
>  此外，我看到您已经可以使用HUG渲染自定义数据集，但HUGS中部分代码只针对于neuman数据集....

我只是简单的copy相关代码并改名，如
```
if os.path.basename(scene name)== '自定义数据'
    manual trans =np.array([-2.25，1.08，8.18])
    manual rot =np.array([90.4,-4.2,-1])/ 180 * np.pi
    manual scale =1.8
```
实际上我自己也不知道会发生什么，反正能训练就行了 ~（懒狗作者是这样的）~

**Comment by fanzhenxuan** [comment]
好的，再次感谢您的代码以及回答！

**Comment by MikeAiJF** [comment]
> 好的，再次感谢您的代码以及回答！

你好，请问你可以进行hugs训练了吗

**Comment by MikeAiJF** [comment]
Length of raw_smpl['pose']: 293
Length of scene.captures: 342
293 342
Traceback (most recent call last):
  File "/project_03/ml-hugs/preprocessForHugs/export_alignment_myself.py", line 626, in <module>
    main(opt)
  File "/project_03/ml-hugs/preprocessForHugs/export_alignment_myself.py", line 564, in main
    assert len(first_104_poses) == len(scene.captures)
AssertionError
这个错误怎么解决，兄弟

**Comment by fanzhenxuan** [comment]
> Length of raw_smpl['pose']: 293 Length of scene.captures: 342 293 342 Traceback (most recent call last): File "/project_03/ml-hugs/preprocessForHugs/export_alignment_myself.py", line 626, in main(opt) File "/project_03/ml-hugs/preprocessForHugs/export_alignment_myself.py", line 564, in main assert len(first_104_poses) == len(scene.captures) AssertionError 这个错误怎么解决，兄弟

很抱歉现在才回复，我目前已经不做这个项目了，你可以去问作者
